#!/bin/bash

PROJECT_BASE_DIR_IN_REPO="/cxx/uart"
TOOLS_DIR_IN_REPO="/cxx/uart/tools"
HELPER_SCRIPTS_DIR_IN_REPO="/cxx/uart/tools/helper_scripts"
BIN_DIR_IN_REPO="/cxx/uart/bin"
CUSTOM_COMMAND="raduino"

REPO_BASE_DIR=$(git rev-parse --show-toplevel)
export RADINO_REPO_BASE_DIR="${REPO_BASE_DIR}${PROJECT_BASE_DIR_IN_REPO}"
export RADINO_TOOLS_DIR="${REPO_BASE_DIR}${TOOLS_DIR_IN_REPO}"
export RADINO_HELPER_SCRIPTS_DIR="${REPO_BASE_DIR}${HELPER_SCRIPTS_DIR_IN_REPO}"
export RADINO_BIN_DIR="${REPO_BASE_DIR}${BIN_DIR_IN_REPO}"
export RADINO_CUSTOM_COMMAND="${CUSTOM_COMMAND}"

#echo "RADINO_REPO_BASE_DIR =${RADINO_REPO_BASE_DIR}"
#echo "RADINO_TOOLS_DIR=${RADINO_TOOLS_DIR}"
#echo "RADINO_BIN_DIR=${RADINO_BIN_DIR}"


