#!/bin/bash

echo "${RADINO_CUSTOM_COMMAND} build menu"
echo "    config"
echo "    setup [arduino, interface, linux, all]"
echo "          set up build area using conan and cmake"
echo "    clean [arduino, interface, linux, all]"
echo "          clean build area"
echo "    build [arduino, interface, linux, all]"
echo "          build target in area created by setup"
echo "    all"
echo "          run commands: clean, setup and build"
echo "    flash [rf-nano, nano]"
echo "          flash arduino"
echo "    experiment"
echo "          run experiment script. typically build, flash and test"
echo "    conan"
echo "          create conan packages"
echo "    test"
