#!/usre/bin/env python3

import os
from libgenerate.common import *

def generateDocumentationReadme():

    commandDocumentationDirectory = "../../../doc/reference-guides/commands/"
    os.makedirs(commandDocumentationDirectory, exist_ok=True)
    readmeFile = commandDocumentationDirectory + "README.md"

    with open(readmeFile, 'w') as outfile:
        outfile.write("# commands\n")
        outfile.write("\n")

def appendDocumentationReadme(commandName):
    commandDocumentationDirectory = "../../../doc/reference-guides/commands/"
    os.makedirs(commandDocumentationDirectory, exist_ok=True)
    readmeFile = commandDocumentationDirectory + "README.md"

    with open(readmeFile, 'a') as outfile:
        outfile.write("- [" + snakecaseToCamelCase(commandName) + "](./" +commandName + ".md)\n")

def generateDocumentationFile(commandName, 
                 commandPayloadFields, 
                 responsePayloadFields):

    commandDocumentationDirectory = "../../../doc/reference-guides/commands/"
    os.makedirs(commandDocumentationDirectory, exist_ok=True)
    commandDocumentationFile = commandDocumentationDirectory + commandName + ".md"

    appendDocumentationReadme(commandName)

    ## class
    with open(commandDocumentationFile, 'w') as outfile:
        outfile.write("# command " + snakecaseToCamelCase(commandName) + "\n")
        outfile.write("\n")
        outfile.write("- [command.hxx](../../../interface/libs/commands/include/cmd/" + commandName + "/command.hxx)\n")
        outfile.write("- [payload.hxx](../../../interface/libs/commands/include/cmd/" + commandName + "/payload.hxx)\n")
        outfile.write("\n")
        outfile.write("## class RaduinoCommand" + snakecaseToCamelCase(commandName) + "\n")
        outfile.write("\n")
        createStringConstructor = False

        outfile.write("### constructors\n")
        outfile.write("\n")
        outfile.write("- RaduinoCommand" + snakecaseToCamelCase(commandName) + "(")
        # add parameters
        items = len(commandPayloadFields)
        for item in commandPayloadFields:
            arraySize = arraySizeFromVariableName(item)
            if(arraySize == 1):
                outfile.write("uint8_t " + item)
            if(arraySize == 2):
                outfile.write("uint16_t " + arrayBasenameFromVariableName(item))
            if(arraySize == 4):
                outfile.write("uint32_t " + arrayBasenameFromVariableName(item))
            if(arraySize > 4):
                createStringConstructor = True
                outfile.write("std::vector<uint8_t> " + arrayBasenameFromVariableName(item))
            items = items - 1
            if items > 0:
                outfile.write(", ")
        outfile.write(")\n")
 
        if createStringConstructor:
            outfile.write("- RaduinoCommand" + snakecaseToCamelCase(commandName) + "(")
            # add parameters
            items = len(commandPayloadFields)
            for item in commandPayloadFields:
                arraySize = arraySizeFromVariableName(item)
                if(arraySize == 1):
                    outfile.write("uint8_t " + item)
                if(arraySize == 2):
                    outfile.write("uint16_t " + arrayBasenameFromVariableName(item))
                if(arraySize == 4):
                    outfile.write("uint32_t " + arrayBasenameFromVariableName(item))
                if(arraySize > 4):
                    outfile.write("std::string " + arrayBasenameFromVariableName(item))
                items = items - 1
                if items > 0:
                    outfile.write(", ")
            outfile.write(")\n")

        outfile.write("\n")
        outfile.write("### member methods in response struct\n")
        outfile.write("\n")

        items = len(responsePayloadFields)
        if items > 0:
            # autogenerated getters 
            for item in responsePayloadFields:
                arraySize = arraySizeFromVariableName(item)
                if(arraySize > 4):
                    outfile.write("- std::string get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")

        outfile.write("- std::string getJson()\n")
        outfile.write("- std::string printResponse()\n")
        outfile.write("- std::string getCommandName()\n")
        outfile.write("- COMMANDS::" + commandName.upper() + "::response_t responseStruct()\n")
        outfile.write("\n")

    ## payloads
    with open(commandDocumentationFile, 'a') as outfile:
        outfile.write("## struct command_t\n")
        outfile.write("\n")
        hasArrays = False

        hasPrintedGetters = False
        items = len(commandPayloadFields)
        if items > 0:
            outfile.write("### methods in command struct\n")
            outfile.write("\n")
            # autogenerated setters
            for item in commandPayloadFields:
                arraySize = arraySizeFromVariableName(item)
                if(arraySize == 1):
                    hasPrintedGetters = True
                    outfile.write("- void set" + item.capitalize() + "(uint8_t value)\n")
                    outfile.write("- uint8_t get" + item.capitalize() + "()\n")
                if(arraySize == 2):
                    hasPrintedGetters = True
                    outfile.write("- void set" + arrayBasenameFromVariableName(item).capitalize() + "(uint16_t value)\n")
                    outfile.write("- uint32_t get" + item.capitalize() + "()\n")
                if(arraySize == 4):
                    hasPrintedGetters = True
                    outfile.write("- void set" + arrayBasenameFromVariableName(item).capitalize() + "(uint32_t value)\n")
                    outfile.write("- uint32_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")
        else:
            outfile.write("- empty command payload\n")
            outfile.write("\n")

        if hasPrintedGetters:
            outfile.write("\n")

        if items>0:
            outfile.write("### variables in command struct\n")
            outfile.write("\n")

            # autogenerated setters
            for item in commandPayloadFields:
                arraySize = arraySizeFromVariableName(item)
                if(arraySize == 1):
                    outfile.write("- uint8_t " + arrayBasenameFromVariableName(item) + "\n")
                else:
                    outfile.write("- uint8_t[" + str(arraySize) + "] " + arrayBasenameFromVariableName(item) + "\n")
            outfile.write("\n")

        outfile.write("## struct response_t\n")
        outfile.write("\n")

        items = len(responsePayloadFields)
        if items > 0:
            outfile.write("### methods in response struct\n")
            outfile.write("\n")
            # autogenerated getters 
            hasPrintedGetters = False
            for item in responsePayloadFields:
                arraySize = arraySizeFromVariableName(item)
                if(arraySize == 1):
                    hasPrintedGetters = True
                    outfile.write("- void set" + item.capitalize() + "(uint8_t value)\n")
                    outfile.write("- uint8_t get" + item.capitalize() + "()\n")
                if(arraySize == 2):
                    hasPrintedGetters = True
                    outfile.write("- void set" + item.capitalize() + "(uint16_t value)\n")
                    outfile.write("- uint16_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")
                if(arraySize == 4):
                    hasPrintedGetters = True
                    outfile.write("- void set" + item.capitalize() + "(uint32_t value)\n")
                    outfile.write("- uint32_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")

            if hasPrintedGetters:
                outfile.write("\n")

            outfile.write("### variables in response struct\n")
            outfile.write("\n")
            # autogenerated setters
            for item in responsePayloadFields:
                arraySize = arraySizeFromVariableName(item)
                if(arraySize == 1):
                    outfile.write("- uint8_t " + arrayBasenameFromVariableName(item) + "\n")
                else:
                    outfile.write("- uint8_t[" + str(arraySize) + "] " + arrayBasenameFromVariableName(item) + "\n")

            outfile.write("\n")

        else:
            outfile.write("- empty response payload\n")
            outfile.write("\n")

