#!/usre/bin/env python3

import os
from libgenerate.common import *

def calculateStructSizeFromNames(commandPayloadByteNames):
    length = 0

    for item in commandPayloadByteNames:
        length = length + arraySizeFromVariableName(item)

    return length 

def generatePayloadFile(commandId, commandName, 
                 commandPayloadByteNames, 
                 responsePayloadByteNames):

    os.makedirs("include/cmd/" + commandName, exist_ok=True)

    payloadFile = f"include/cmd/{commandName}/payload.hxx"

    # header and open both namespaces
    with open(payloadFile, 'w') as outfile:
        outfile.write("#pragma once\n")
        outfile.write("\n")
        outfile.write("// This file is generated with the script: `interface/libs/commands/generate.py`\n")
        outfile.write("\n")

        outfile.write("#include <cmd/command_id.hxx>\n")
        outfile.write("\n")
        outfile.write("namespace COMMANDS {\n")
        outfile.write("\n")
        outfile.write("namespace " + commandName.upper() + " {\n")

    # add constexpr
    with open(payloadFile, 'a') as outfile:
        outfile.write("    constexpr uint8_t COMMAND_LENGTH = " + str(calculateStructSizeFromNames(commandPayloadByteNames)) + ";\n")
        outfile.write("    constexpr uint8_t RESPONSE_LENGTH = " + str(calculateStructSizeFromNames(responsePayloadByteNames)) + ";\n")
        outfile.write("\n")
        outfile.write("    static_assert(COMMAND_LENGTH < COMMANDS::MAX_PAYLOAD_LENGTH, \"COMMAND_LENGTH larger than max payload\");\n")
        outfile.write("    static_assert(RESPONSE_LENGTH < COMMANDS::MAX_PAYLOAD_LENGTH, \"RESPONSE_LENGTH larger than max payload\");\n")
        outfile.write("\n")

    # add command struct
    with open(payloadFile, 'a') as outfile:
        outfile.write("    typedef struct command {\n")
        outfile.write("        command()\n")
        outfile.write("        {\n")
        outfile.write("            OI = static_cast<uint8_t>(COMMANDS::OI::" + commandName.upper() + ");\n")
        outfile.write("            OL = COMMAND_LENGTH;\n")

        # loop through commandPayloadByteNames
        index = 2
        for item in commandPayloadByteNames:
            arraySize = arraySizeFromVariableName(item)
            if(arraySize > 1):
                outfile.write("            for (uint8_t i = 0; i < " + str(arraySize) + "; i++) {\n")
                outfile.write("                " + arrayBasenameFromVariableName(item) + "[i] = 0;\n")
                outfile.write("            }\n")
            else:
                outfile.write("            " + item + " = 0;\n")
            index = index + arraySize

        outfile.write("        }\n")
        outfile.write("\n")
        outfile.write("        command(uint8_t* cmd)\n")
        outfile.write("        {\n")
        outfile.write("            OI = cmd[0];\n")
        outfile.write("            OL = cmd[1];\n")

        # loop through commandPayloadByteNames
        index = 2
        for item in commandPayloadByteNames:
            arraySize = arraySizeFromVariableName(item)
            if(arraySize > 1):
                outfile.write("            for (uint8_t i = 0; i < " + str(arraySize) + "; i++) {\n")
                outfile.write("                " + arrayBasenameFromVariableName(item) + "[i] = cmd[" + str(index) + " + i];\n")
                outfile.write("            }\n")
            else:
                outfile.write("            " + item + " = cmd[" + str(index) + "];\n")
            index = index + arraySize

        outfile.write("        }\n")
        outfile.write("\n")

        # autogenerated getters and setters
        for item in commandPayloadByteNames:

            arraySize = arraySizeFromVariableName(item)
            if(arraySize == 1):
                outfile.write("        uint8_t get" + item.capitalize() + "()\n")
                outfile.write("        {\n")
                outfile.write("            return (" + item + ");\n")
                outfile.write("        }\n")
                outfile.write("\n")
                outfile.write("        void set" + item.capitalize() + "(uint8_t val)\n")
                outfile.write("        {\n")
                outfile.write("            " + item + " = val;\n")
                outfile.write("        }\n")
                outfile.write("\n")
            if(arraySize == 2):
                outfile.write("        uint16_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")
                outfile.write("        {\n")
                outfile.write("            return (((uint16_t)" + arrayBasenameFromVariableName(item) + "[1]) << 8 | " + arrayBasenameFromVariableName(item) + "[0]);\n")
                outfile.write("        }\n")
                outfile.write("\n")
                outfile.write("        void set" + arrayBasenameFromVariableName(item).capitalize() + "(uint16_t val)\n")
                outfile.write("        {\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[1] = (uint8_t)(val >> 8);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[0] = (uint8_t)val;\n")
                outfile.write("        }\n")
                outfile.write("\n")
            if(arraySize == 4):
                outfile.write("        uint32_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")
                outfile.write("        {\n")
                outfile.write("            return (((uint32_t)" + arrayBasenameFromVariableName(item) + "[2]) << 16 | ((uint32_t)" + arrayBasenameFromVariableName(item) + "[2]) << 16 | ((uint32_t)" + arrayBasenameFromVariableName(item) + "[1]) << 8 | " + arrayBasenameFromVariableName(item) + "[0]);\n")
                outfile.write("        }\n")
                outfile.write("\n")
                outfile.write("        void set" + arrayBasenameFromVariableName(item).capitalize() + "(uint32_t val)\n")
                outfile.write("        {\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[3] = (uint8_t)(val >> 24);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[2] = (uint8_t)(val >> 15);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[1] = (uint8_t)(val >> 8);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[0] = (uint8_t)val;\n")
                outfile.write("        }\n")
                outfile.write("\n")


        outfile.write("        uint8_t OI;\n")
        outfile.write("        uint8_t OL;\n")

        # loop through commandPayloadByteNames
        index = 2
        for item in commandPayloadByteNames:
            outfile.write("        uint8_t " + item + ";\n")
            index = index + 1

        outfile.write("    } command_t;\n")
        outfile.write("\n")

    # add response struct
    with open(payloadFile, 'a') as outfile:
        outfile.write("    typedef struct response {\n")
        outfile.write("        response()\n")
        outfile.write("        {\n")
        outfile.write("            OI = static_cast<uint8_t>(COMMANDS::OI::" + commandName.upper() + ");\n")
        outfile.write("            OL = RESPONSE_LENGTH;\n")

        # loop through commandPayloadByteNames
        index = 2
        for item in responsePayloadByteNames:
            arraySize = arraySizeFromVariableName(item)
            if(arraySize > 1):
                outfile.write("            for (uint8_t i = 0; i < " + str(arraySize) + "; i++) {\n")
                outfile.write("                " + arrayBasenameFromVariableName(item) + "[i] = 0;\n")
                outfile.write("            }\n")
            else:
                outfile.write("            " + item + " = 0;\n")
            index = index + arraySize

        outfile.write("        }\n")
        outfile.write("\n")
        outfile.write("        response(uint8_t* res)\n")
        outfile.write("        {\n")
        outfile.write("            OI = res[0];\n")
        outfile.write("            OL = res[1];\n")

        # loop through commandPayloadByteNames
        index = 2
        for item in responsePayloadByteNames:
            arraySize = arraySizeFromVariableName(item)
            if(arraySize > 1):
                outfile.write("            for (uint8_t i = 0; i < " + str(arraySize) + "; i++) {\n")
                outfile.write("                " + arrayBasenameFromVariableName(item) + "[i] = res[" + str(index) + " + i];\n")
                outfile.write("            }\n")
            else:
                outfile.write("            " + item + " = res[" + str(index) + "];\n")
            index = index + arraySize

        outfile.write("        }\n")
        outfile.write("\n")
        outfile.write("        void serialize(uint8_t* response)\n")
        outfile.write("        {\n")
        outfile.write("            response[0] = OI;\n")
        outfile.write("            response[1] = OL;\n")

        # loop through commandPayloadByteNames
        index = 2
        for item in responsePayloadByteNames:
            arraySize = arraySizeFromVariableName(item)
            if(arraySize > 1):
                outfile.write("            for (uint8_t i = 0; i < " + str(arraySize) + "; i++) {\n")
                outfile.write("                response[" + str(index) + " + i] = " + arrayBasenameFromVariableName(item) + "[i];\n")
                outfile.write("            }\n")
            else:
                outfile.write("            response[" + str(index) + "] = " + item + ";\n")
            index = index + arraySize

        outfile.write("        }\n")
        outfile.write("\n")

        # autogenerated getters and setters
        for item in responsePayloadByteNames:

            arraySize = arraySizeFromVariableName(item)
            if(arraySize == 1):
                outfile.write("        uint8_t get" + item.capitalize() + "()\n")
                outfile.write("        {\n")
                outfile.write("            return (" + item + ");\n")
                outfile.write("        }\n")
                outfile.write("\n")
                outfile.write("        void set" + item.capitalize() + "(uint8_t val)\n")
                outfile.write("        {\n")
                outfile.write("            " + item + " = val;\n")
                outfile.write("        }\n")
                outfile.write("\n")
            if(arraySize == 2):
                outfile.write("        uint16_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")
                outfile.write("        {\n")
                outfile.write("            return (((uint16_t)" + arrayBasenameFromVariableName(item) + "[1]) << 8 | " + arrayBasenameFromVariableName(item) + "[0]);\n")
                outfile.write("        }\n")
                outfile.write("\n")
                outfile.write("        void set" + arrayBasenameFromVariableName(item).capitalize() + "(uint16_t val)\n")
                outfile.write("        {\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[1] = (uint8_t)(val >> 8);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[0] = (uint8_t)val;\n")
                outfile.write("        }\n")
                outfile.write("\n")
            if(arraySize == 4):
                outfile.write("        uint32_t get" + arrayBasenameFromVariableName(item).capitalize() + "()\n")
                outfile.write("        {\n")
                outfile.write("            return (((uint32_t)" + arrayBasenameFromVariableName(item) + "[3]) << 24 | ((uint32_t)" + arrayBasenameFromVariableName(item) + "[2]) << 16 | ((uint32_t)" + arrayBasenameFromVariableName(item) + "[1]) << 8 | " + arrayBasenameFromVariableName(item) + "[0]);\n")
                outfile.write("        }\n")
                outfile.write("\n")
                outfile.write("        void set" + arrayBasenameFromVariableName(item).capitalize() + "(uint32_t val)\n")
                outfile.write("        {\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[3] = (uint8_t)(val >> 24);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[2] = (uint8_t)(val >> 16);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[1] = (uint8_t)(val >> 8);\n")
                outfile.write("            " + arrayBasenameFromVariableName(item) + "[0] = (uint8_t)val;\n")
                outfile.write("        }\n")
                outfile.write("\n")


        outfile.write("        uint8_t OI;\n")
        outfile.write("        uint8_t OL;\n")

        # loop through responsePayloadByteNames
        index = 2
        for item in responsePayloadByteNames:
            outfile.write(f"        uint8_t {item};\n")
            index = index + 1

        outfile.write("\n")
        outfile.write("    } response_t;\n")

    # close both namespaces
    with open(payloadFile, 'a') as outfile:
        outfile.write("}\n")
        outfile.write("\n")
        outfile.write("} // namespace commands\n")

