#!/bin/bash

echo "${RADINO_CUSTOM_COMMAND} build menu"
echo "    format    : <code>"
echo "    lint      : <doc>"
echo "    generate  : <commands>"
echo "                run code generator for commands"
echo "    dockerapp : <build|run>"
echo "                build or run a container with raduino apps"
echo "    devbox    : "
echo "                start up a container where you can build and run this software"
echo "    podmand   : alternative to docker"
echo "    tool      : <personalize|gateway|node|test|mqtt|power>"
echo "    setup     : <arduino|interface|linux|all>"
echo "                set up build area using conan and cmake"
echo "    clean     : <arduino|interface|linux|all>"
echo "                clean build area"
echo "    build     : <arduino|interface|linux|all>"
echo "                build target in area created by setup"
echo "    all       : run commands: clean, setup and build"
echo "    release   : <bump|push|detect|latest>"
echo "    flash     : <rf-nano|nano-pro>"
echo "                flash arduino"
echo "    mqtt      : <interval|text|subscribe|start|stop>"
echo "    conan     : create conan packages"
echo "    analyze   : analyze arduino.elf"
