#!/bin/bash

echo "${RADINO_CUSTOM_COMMAND} build menu"
echo ""
echo "build:"
echo " docker-devbox : <local|remote> <clean|build|bash|all>"
echo "                 start up a container where you can build"
echo " podman-devbox : <local|remote> <clean|build|bash|all>"
echo "                 start up a container where you can build"
echo "    clean      : <arduino|interface|linux|all>"
echo "                 clean build area"
echo "    setup      : <arduino|interface|linux|all>"
echo "                 set up build area using conan and cmake"
echo "    build      : <arduino|interface|linux|all>"
echo "                 build target in area created by setup"
echo "    all        : run commands: clean, setup and build for all targets"
echo "    conan      : <interface|arduino|linux|all>"
echo "                 create conan packages"
echo "    release    : <bump|push|detect|latest>"
echo "                 work with version tags"
echo ""
echo "testing:"
echo "    flash      : <rf-nano|nano-pro>"
echo "                 flash arduino"
echo "    docker-app : <local|remote> <build|run>"
echo "                 build or run a container with raduino apps"
echo "    podman-app : <local|remote>"
echo "                 alternative to docker"
echo "    tool       : <personalize|gateway|node|test|mqtt|power>"
echo "                 shortcut to compiled linux app"
echo "    mqtt       : <interval|text|subscribe|start|stop>"
echo "                 shortcuts for mosquitto, mosquitto_pub and mosquito_sub"
echo ""
echo "misc:"
echo "    generate   : <commands> run code generator"
echo "    analyze    : analyze arduino.elf"
echo "    format     : <changed|all>"
echo "    lint       : markdown lint"
