#!/usr/bin/env python3

from libgenerate.raduinocommand import raduinoCommandGenerator

generator = raduinoCommandGenerator()

# command definitions
generator.add(2, "blink", [], [])
generator.add(3, "sha1", ["data[20]"], ["data[20]"])
generator.add(4, "hotp", [], ["data[20]"])
generator.add(5, "eeprom_write", ["address[2]", "data"], ["address[2]", "data"])
generator.add(6, "eeprom_read", ["address[2]"], ["address[2]", "data"])
generator.add(7, "aes", ["type", "data[16]"], ["type", "data[16]"])
generator.add(8, "pwm", ["port", "pin", "value"], ["port", "pin", "value"])
generator.add(9, "random", [], ["data[16]"])
generator.add(10, "debug", [], ["data[32]"])
generator.add(11, "gpio", [], ["portB", "portC", "portD"])
generator.add(12, "i2c_write", ["device", "registerAddress[2]", "length", "data[16]"], [])
generator.add(13, "i2c_read", ["device", "registerAddress[2]", "length"], ["device", "registerAddress[2]", "length", "data[16]"])
generator.add(14, "ina219", [], ["current[2]", "voltage[2]"])
generator.add(15, "ds18b20", [], ["temperature[2]"])
generator.add(16, "set_key", ["keyId", "keyValue[16]"], [])
generator.add(17, "set_device_name", ["name[16]"], [])
generator.add(18, "get_device_name", [], ["nameString[16]"])
generator.add(19, "ws2812b", ["red[8]", "green[8]", "blue[8]"], [])
generator.add(20, "ssd1306", ["line", "data[16]"], [])
generator.add(21, "timer", [], ["pulseWidth[2]"])
generator.add(22, "spi_read", ["reg", "length"], ["reg", "length", "data[32]"])
generator.add(23, "spi_write", ["reg", "length", "data[32]"], [])
generator.add(24, "nrf24l01_init", ["txAddr[5]", "rxAddr[5]", "rfChannel", "gateway"], [])
generator.add(25, "nrf24l01_read", ["length", "data[32]"], ["length", "data[32]"])
generator.add(26, "nrf24l01_write", ["length", "data[32]"], ["length", "data[32]"])
generator.add(27, "radio_uart", ["mode"], [])
generator.add(28, "vcc", [], ["vcc[2]"])
generator.add(29, "sleep", ["delay[4]"], [])
generator.add(30, "wakeup", ["checkAttentionFlag"], ["discovered"])
generator.add(31, "set_node_address", ["nodeAddress"], [])
generator.add(32, "keep_alive", ["time"], [])
generator.add(33, "ping", [], [])
generator.add(34, "quadrature_encoder", [], ["countnegative[2]", "countpositive[2]", "switchposition", "switchcount[2]"])
generator.add(35, "get_version", [], ["versionString[32]"])
generator.add(36, "get_statistics", [], ["commandsParsed[2]", "uartRx[4]", "uartTx[4]", "radioRx[4]", "radioTx[4]", "restarts[2]"])
generator.add(37, "require_transport_encryption", ["value"], [])
generator.add(38, "set_radio_role", ["isRadioNode"], [])
generator.add(39, "soft_reset", [], [])
generator.add(40, "unlock_session", [], [])
generator.add(41, "set_unique_id", ["id[4]"], [])
generator.add(42, "get_unique_id", [], ["id[4]"])
generator.add(43, "get_lsm303d", [], ["accelerometerX[2]", "accelerometerY[2]", "accelerometerZ[2]"])
generator.add(44, "set_attached_devices_csv_string", ["csvString[64]"], [])
generator.add(45, "get_attached_devices_csv_string", [], ["csvString[64]"])
generator.add(46, "get_last_device_id_seen", [], ["id[4]"])

# close files
generator.closeFiles()

