#pragma once

#include <common/uartCommandBase.hpp>

#include <aes/command.hpp>
#include <blink/command.hpp>
#include <debug/command.hpp>
#include <ds18b20/command.hpp>
#include <eeprom_read/command.hpp>
#include <eeprom_write/command.hpp>
#include <gpio/command.hpp>
#include <hotp/command.hpp>
#include <i2c_read/command.hpp>
#include <i2c_write/command.hpp>
#include <ina219/command.hpp>
#include <pwm/command.hpp>
#include <random/command.hpp>
#include <sha1/command.hpp>
#include <set_key/command.hpp>
#include <set_device_info/command.hpp>
#include <get_device_info/command.hpp>
#include <ws2812b/command.hpp>
#include <ssd1306/command.hpp>
#include <timer/command.hpp>
#include <spi_read/command.hpp>
#include <spi_write/command.hpp>
#include <nrf24l01_init/command.hpp>
#include <nrf24l01_read/command.hpp>
#include <nrf24l01_write/command.hpp>
#include <radio_uart/command.hpp>
#include <vcc/command.hpp>
#include <sleep/command.hpp>
#include <wakeup/command.hpp>
#include <set_node_address/command.hpp>
#include <keep_alive/command.hpp>
#include <ping/command.hpp>
