#pragma once

#include <stdint.h>

#include <common/command_id.hpp>
#include <aes/payload.hpp>
#include <blink/payload.hpp>
#include <debug/payload.hpp>
#include <ds18b20/payload.hpp>
#include <eeprom_read/payload.hpp>
#include <eeprom_write/payload.hpp>
#include <get_device_info/payload.hpp>
#include <gpio/payload.hpp>
#include <hotp/payload.hpp>
#include <i2c_read/payload.hpp>
#include <i2c_write/payload.hpp>
#include <ina219/payload.hpp>
#include <keep_alive/payload.hpp>
#include <nrf24l01_init/payload.hpp>
#include <nrf24l01_read/payload.hpp>
#include <nrf24l01_write/payload.hpp>
#include <ping/payload.hpp>
#include <pwm/payload.hpp>
#include <quadrature_encoder/payload.hpp>
#include <radio_uart/payload.hpp>
#include <random/payload.hpp>
#include <set_device_info/payload.hpp>
#include <set_key/payload.hpp>
#include <set_node_address/payload.hpp>
#include <sha1/payload.hpp>
#include <sleep/payload.hpp>
#include <spi_read/payload.hpp>
#include <spi_write/payload.hpp>
#include <ssd1306/payload.hpp>
#include <timer/payload.hpp>
#include <vcc/payload.hpp>
#include <wakeup/payload.hpp>
#include <ws2812b/payload.hpp>
