FROM ubuntu:22.04

RUN apt-get update 
RUN apt-get install -y build-essential cmake ccache 
RUN apt-get install -y gcc-avr binutils-avr avr-libc avrdude
RUN apt-get install -y git vim bc
RUN apt-get install -y python3 python3-pip
RUN pip3 install conan==1.57

RUN useradd -ms /bin/bash raduino
USER raduino
WORKDIR /home/raduino/
