FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y --only-upgrade libstdc++6
RUN apt-get install -y avrdude

COPY bin/* /bin/
COPY tools/scripts/raduino-flash.sh /bin/

RUN useradd -ms /bin/bash raduino
USER raduino
