name: Build and Push Docker Image from Tag

on:
  push:
    branches:
      - 'main'
    paths:
      - 'tools/docker/dev/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to write to GitHub Packages (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has necessary permissions

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # The name of your image repository
          tags: |
            type=semver,pattern={{version}} # Extracts semantic version from the Git tag (e.g., v1.0.0 -> 1.0.0)
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./tools/docker/dev/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Uses the tags generated by the metadata action
          labels: ${{ steps.meta.outputs.labels }}-devbox
